# Setup
title:        光辉岁月 BLOG
tagline:      Keep Calm and Carry On
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       ZHONG.C.Y
  url:        http://www.ivivi.com.cn

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown