# Setup
title:        
tagline:      光辉岁月 Blog
baseurl:      "不积跬步 无以至千里"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Davi zhong
  url:        www.ivivi.com.cn

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown