# Setup
title:        Keep Calm and Carry On
tagline:      光辉岁月 BLOG
baseurl:      "http://i0.hdslb.com/bfs/space/e4a20d9d23c80751534bdb8eb7557e9c3fc1746e.png"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       ZHONG.C.Y
  url:        http://www.ivivi.com.cn

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown